# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '../platforms'

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cptext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.cptext.setGeometry(QtCore.QRect(110, 280, 361, 51))
        self.cptext.setObjectName("cptext")
        self.de = QtWidgets.QPushButton(self.centralwidget)
        self.de.setGeometry(QtCore.QRect(570, 250, 75, 23))
        self.de.setObjectName("de")
        self.plain = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plain.setGeometry(QtCore.QRect(110, 120, 361, 51))
        self.plain.setObjectName("plain")
        self.matrix = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.matrix.setGeometry(QtCore.QRect(110, 180, 451, 51))
        self.matrix.setObjectName("matrix")
        self.key = QtWidgets.QTextEdit(self.centralwidget)
        self.key.setGeometry(QtCore.QRect(110, 240, 241, 31))
        self.key.setObjectName("key")
        self.en = QtWidgets.QPushButton(self.centralwidget)
        self.en.setGeometry(QtCore.QRect(570, 220, 75, 23))
        self.en.setObjectName("en")
        self.taokey = QtWidgets.QPushButton(self.centralwidget)
        self.taokey.setGeometry(QtCore.QRect(570, 190, 75, 23))
        self.taokey.setObjectName("taokey")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.de.setText(_translate("MainWindow", "PushButton"))
        self.en.setText(_translate("MainWindow", "PushButton"))
        self.taokey.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
